version: '3.8'

services:
  streamlit-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    # command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
